name: CML
on: [push]
jobs:
  train-and-report-sarcasm:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
      
      - uses: allegroai/clearml-github-action@v1
      - name: setup-clearml
        with:
          access_key: ${{ secrets.CLEARML_ACCESS_KEY }}
          secret_key: ${{ secrets.CLEARML_SECRET_KEY }}
        run: |
          pip install -r requirements.txt
          python train_sklearn.py  # generate plot.png

          # Create CML report
          cat sklearn_metrics.txt >> report.md
          echo '![](./sklearn_confusion_matrix/confusion_matrix.png "Confusion Matrix")' >> report.md
          cml comment create report.md