name: CML
on: [push]
jobs:
  train-and-report-sarcasm:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
          CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_SECRET_KEY }}
          CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ClearML
        run: |
          python -m pip install --upgrade pip clearml pandas tabulate github3.py Jinja2
      - name: Start the task
        id: launch_task
        run: |
          pip install -r requirements.txt
          python train_sklearn.py  # generate plot.png

          # Create CML report
          cat sklearn_metrics.txt >> report.md
          echo '![](./sklearn_confusion_matrix/confusion_matrix.png "Confusion Matrix")' >> report.md
          cml comment create report.md

        